# -*- coding: utf-8 -*-
"""baselines_tfidf

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwjFi43WZklvXwhYa5e1yrELbGuz44Zo
"""

import pandas as pd
from sklearn.model_selection import GroupShuffleSplit
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score

df = pd.read_csv("https://raw.githubusercontent.com/CrisLavalley/socio-emotional-conversational-framework/refs/heads/main/data/dataset_anonimizado.csv")

labels = ["ansiedad","frustración","tristeza","calma","esperanza","alegría"]
label2id = {l:i for i,l in enumerate(labels)}
df["label"] = df["emocion"].map(label2id)

gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=37)
train_idx, test_idx = next(gss.split(df["texto"], df["label"], groups=df["id_sesion"]))

train_df = df.iloc[train_idx]
test_df = df.iloc[test_idx]

model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2))),
    ("clf", LogisticRegression(max_iter=3000))
])

model.fit(train_df["texto"], train_df["label"])
y_pred = model.predict(test_df["texto"])

print("Accuracy:", accuracy_score(test_df["label"], y_pred))
print("Macro-F1:", f1_score(test_df["label"], y_pred, average="macro"))