# -*- coding: utf-8 -*-
"""pipeline_reproducible_beto

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rvEbXS5BZ03J25lqYibiVoKXOVj5P2Q
"""

# ============================================================
# REPRODUCIBLE DATA MINING PIPELINE FOR SOCIO-EMOTIONAL ANALYSIS
# ============================================================
# Author: Cristhianne De León Vargas
# Context: IJCOPI Article – Reproducible Framework
#
# This script implements a reproducible pipeline for:
#   (1) Inter-annotator agreement validation
#   (2) Socio-emotional classification (BETO-light)
#   (3) Robust evaluation with uncertainty estimation
#   (4) Auditable outputs for replication (Supplement S1)
#
# The design follows the principles of:
#   - Traceability
#   - Reproducibility
#   - Privacy-aware processing
#   - Robust evaluation (session-based split + bootstrap CI)
# ============================================================

# =========================
# 0) DEPENDENCIES
# =========================
# For Colab usage. For local environments, install manually.
!pip -q install transformers datasets accelerate evaluate scikit-learn

# =========================
# 1) IMPORTS
# =========================
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch

from sklearn.metrics import (
    cohen_kappa_score,
    classification_report,
    accuracy_score,
    f1_score,
    confusion_matrix,
    ConfusionMatrixDisplay
)

from sklearn.model_selection import GroupShuffleSplit
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

# =========================
# 2) REPRODUCIBILITY SETUP
# =========================
# A fixed random seed ensures full reproducibility across:
#   - dataset splitting
#   - model initialization
#   - bootstrap resampling
SEED = 37
np.random.seed(SEED)
torch.manual_seed(SEED)

# ============================================================
# 3) DATA SOURCES (LOCAL + REMOTE FALLBACK)
# ============================================================

# Remote dataset URL (GitHub)
DATASET_URL = "https://raw.githubusercontent.com/CrisLavalley/socio-emotional-conversational-framework/refs/heads/main/data/dataset_anonimizado.csv"

# Local paths
DATASET_PATH = "dataset_anonimizado.csv"
ANNOTATION_PATH = "anotacion_doble.csv"

# =========================
# 4) LABEL CONFIGURATION
# =========================
# Emotion taxonomy used in the study
LABELS = [
    "ansiedad",
    "frustración",
    "tristeza",
    "calma",
    "esperanza",
    "alegría"
]

label2id = {l: i for i, l in enumerate(LABELS)}
id2label = {i: l for l, i in label2id.items()}

# ============================================================
# PART A: INTER-ANNOTATOR AGREEMENT
# ============================================================

# =========================
# 5) LOAD ANNOTATION DATA
# =========================
# This dataset contains double-annotated messages used
# to estimate labeling reliability.

# ============================================================
# SAFE LOAD: ANNOTATION DATA (OPTIONAL)
# ============================================================
if os.path.exists(ANNOTATION_PATH):
    df_ann = pd.read_csv(ANNOTATION_PATH)

    # Normalize labels to reduce non-informative variability
    df_ann["etiqueta"] = df_ann["etiqueta"].astype(str).str.strip().str.lower()
    df_ann["anotador_id"] = df_ann["anotador_id"].astype(str).str.strip()

    print("Annotation dataset loaded.")

else:
    df_ann = None
    print("Annotation dataset not found. Skipping agreement step.")

# =========================
# 6) COHEN'S KAPPA
# =========================
# Cohen’s Kappa measures agreement between two annotators,
# correcting for chance agreement.
if df_ann is not None:

    pv = df_ann.pivot_table(
        index="id_mensaje",
        columns="anotador_id",
        values="etiqueta",
        aggfunc="first"
    )

    if pv.shape[1] == 2:
        a1, a2 = pv.columns
        pv_clean = pv.dropna()

        kappa = cohen_kappa_score(pv_clean[a1], pv_clean[a2])

        print("\nCohen's Kappa =", round(kappa, 4))
    else:
        print("Cohen's Kappa requires exactly 2 annotators.")

else:
    pv = None
    print("Inter-annotator agreement not computed.")

# =========================
# 7) KRIPPENDORFF'S ALPHA
# =========================
def krippendorff_alpha_nominal(data):
    """
    Krippendorff’s Alpha for nominal data.

    This implementation supports:
        - Multiple annotators
        - Missing values
        - Categorical labels

    Returns:
        Alpha coefficient (agreement reliability)
    """
    cats = [v for row in data for v in row if v == v]
    if len(cats) == 0:
        return np.nan

    cats = np.array(cats, dtype=object)
    uniq, counts = np.unique(cats, return_counts=True)
    freq = dict(zip(uniq, counts))
    N = counts.sum()

    # Observed disagreement
    Do_num, Do_den = 0.0, 0.0
    for row in data:
        vals = [v for v in row if v == v]
        for i in range(len(vals)):
            for j in range(i + 1, len(vals)):
                Do_num += 0 if vals[i] == vals[j] else 1
                Do_den += 1

    if Do_den == 0:
        return np.nan

    Do = Do_num / Do_den

    # Expected disagreement
    De = 1.0 - sum((freq[c] / N) ** 2 for c in uniq)

    return 1.0 if De == 0 else 1.0 - (Do / De)

if pv is not None:
    alpha = krippendorff_alpha_nominal(pv.to_numpy(dtype=object))
    print("Krippendorff's Alpha =", round(alpha, 4))
else:
    print("Krippendorff's Alpha not computed.")

# ============================================================
# LOAD DATASET
# ============================================================

if os.path.exists(DATASET_PATH):
    print("Loading dataset from local file...")
    df = pd.read_csv(DATASET_PATH)
else:
    print("Local dataset not found. Loading from GitHub...")
    df = pd.read_csv(DATASET_URL)

# ============================================================
# DATA PREPARATION
# ============================================================

df["texto"] = df["texto"].astype(str)
df["id_sesion"] = df["id_sesion"].astype(str)
df["emocion"] = df["emocion"].astype(str).str.strip().str.lower()

df["label"] = df["emocion"].map(label2id)
df = df.dropna(subset=["label"]).reset_index(drop=True)
df["label"] = df["label"].astype(int)

# ============================================================
# 8) SESSION-BASED SPLIT (CRITICAL DESIGN DECISION)
# ============================================================
# GroupShuffleSplit prevents data leakage:
# messages from the same session cannot appear in both
# training and test sets.
gss = GroupShuffleSplit(n_splits=1, test_size=0.25, random_state=SEED)
train_idx, test_idx = next(gss.split(df["texto"], df["label"], groups=df["id_sesion"]))

train_df = df.iloc[train_idx].reset_index(drop=True)
test_df = df.iloc[test_idx].reset_index(drop=True)

# ============================================================
# 9) TOKENIZATION (BETO)
# ============================================================
model_name = "dccuchile/bert-base-spanish-wwm-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(batch):
    return tokenizer(
        batch["texto"],
        truncation=True,
        padding="max_length",
        max_length=128
    )

train_ds = Dataset.from_pandas(train_df[["texto", "label"]]).map(tokenize, batched=True)
test_ds = Dataset.from_pandas(test_df[["texto", "label"]]).map(tokenize, batched=True)

train_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])
test_ds.set_format(type="torch", columns=["input_ids", "attention_mask", "label"])

# ============================================================
# 10) MODEL (BETO-LIGHT)
# ============================================================
model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=len(LABELS),
    id2label=id2label,
    label2id=label2id
)

# ============================================================
# 11) METRICS
# ============================================================
def compute_metrics(eval_pred):
    logits, y_true = eval_pred
    y_pred = np.argmax(logits, axis=1)

    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "macro_f1": f1_score(y_true, y_pred, average="macro"),
        "weighted_f1": f1_score(y_true, y_pred, average="weighted")
    }

# ============================================================
# 12) TRAINING CONFIG
# ============================================================
args = TrainingArguments(
    output_dir="./beto_out",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="macro_f1",
    seed=SEED
)

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_ds,
    eval_dataset=test_ds,
    processing_class=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

# ============================================================
# 13) EVALUATION
# ============================================================
pred = trainer.predict(test_ds)

logits = pred.predictions
y_true = pred.label_ids
y_pred = np.argmax(logits, axis=1)

print(classification_report(y_true, y_pred, target_names=LABELS))

# ============================================================
# 14) CONFUSION MATRIX
# ============================================================
cm = confusion_matrix(y_true, y_pred, labels=list(range(len(LABELS))))

disp = ConfusionMatrixDisplay(cm, display_labels=LABELS)
disp.plot(xticks_rotation=45)
plt.title("Confusion Matrix - BETO-light")
plt.tight_layout()
plt.savefig("matriz_confusion_beto.png", dpi=200)
plt.show()

# ============================================================
# 15) PROBABILITIES + SUPPLEMENT (S1)
# ============================================================
def softmax(x):
    e = np.exp(x - np.max(x, axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)

probs = softmax(logits)

sup = test_df.copy().reset_index(drop=True)
sup["y_true_id"] = y_true
sup["y_pred_id"] = y_pred
sup["y_true"] = [id2label[i] for i in y_true]
sup["y_pred"] = [id2label[i] for i in y_pred]
sup["prob_max"] = probs.max(axis=1)

for i, lab in enumerate(LABELS):
    sup[f"prob_{lab}"] = probs[:, i]

# This file corresponds to Supplementary Material S1
sup.to_csv("suplemento_predicciones_beto.csv", index=False, encoding="utf-8-sig")

# ============================================================
# 16) BOOTSTRAP CONFIDENCE INTERVALS
# ============================================================
def bootstrap_ci(metric_fn, y_true, y_pred, n_boot=2000):
    rng = np.random.default_rng(SEED)
    stats = []
    n = len(y_true)

    for _ in range(n_boot):
        idx = rng.choice(n, n, replace=True)
        stats.append(metric_fn(y_true[idx], y_pred[idx]))

    return np.percentile(stats, [2.5, 97.5])

acc = accuracy_score(y_true, y_pred)
acc_ci = bootstrap_ci(accuracy_score, y_true, y_pred)

macro_f1 = f1_score(y_true, y_pred, average="macro")
f1_ci = bootstrap_ci(lambda a, b: f1_score(a, b, average="macro"), y_true, y_pred)

weighted_f1 = f1_score(y_true, y_pred, average="weighted")

print("\nAccuracy:", acc, "CI95%", acc_ci)
print("Macro-F1:", macro_f1, "CI95%", f1_ci)
print("Weighted-F1:", weighted_f1)

# ============================================================
# 17) SAVE RESULTS TABLE
# ============================================================
results = pd.DataFrame([{
    "Modelo": "BETO-light (fine-tuning)",
    "Acc": acc,
    "Acc_CI95_low": acc_ci[0],
    "Acc_CI95_high": acc_ci[1],
    "MacroF1": macro_f1,
    "MacroF1_CI95_low": f1_ci[0],
    "MacroF1_CI95_high": f1_ci[1],
    "WeightedF1": weighted_f1,
    "n_test": len(y_true)
}])

results.to_csv("resultados_beto_tabla42_con_ic.csv", index=False, encoding="utf-8-sig")

print("\nSaved files:")
print("- matriz_confusion_beto.png")
print("- suplemento_predicciones_beto.csv")
print("- resultados_beto_tabla42_con_ic.csv")